### PR TITLE
AltBeacon Library Update

### LINKED ISSUE #31: The library does not work on Android 12
Any solution to this error, it won't let me install the application in android 12

`Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1325317315.tmp/base.apk (at Binary XML file line #90): org.altbeacon.beacon.startup.StartupBroadcastReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]`

@pszklarska 

Thank you for the development of the library.

### PR DESCRIPTION
**Pull request by praveen-gm**
- Updated AltBeacon Library from 2.17.1 to 2.19.3, to support android apps targeting SDK 31 and above
  `Apps Targeting S+ (version 31 and above) requires that an explicit value for android:exported`
   Closes #31   
- Updated Kotlin Version to 1.6.10
- Updated CHANGELOG & pubspec version to 0.3.1
- Updated Example App to run on the latest Flutter SDK and changed app's target SDK to 31

- All Tests Passed
- Tested on Physical Devices
  - Samsung A10s (Android 11)
  - Nokia 8.1 (Android 11)

### CODE REVIEW

**Comment by pszklarska** [comment]
Hi @praveen-gm! Thank you for your PR and I'm sorry for the delay.

It looks good to me. However, there was some issue with the CI. It should be fixed by now, but GitHub Actions won't allow me to re-run it (as it's been more than 30 days), so can you please update your PR and push your changes again to trigger the CI?

**Comment by praveen-gm** [comment]
Hi @pszklarska, I've updated my PR to trigger the CI. It looks like the Pre-publishing failed due to missing credentials. Let me know if there's anything else.

**Comment by pszklarska** [comment]
Awesome, thanks @praveen-gm! 
I fixed this issue with CI, so all you have to do now is to fix one conflict in the `example/pubspec.lock` and I'd be happy to merge your PR!

**Comment by praveen-gm** [comment]
@pszklarska, I've pulled the changes from master and resolved conflicts at `example/pubspec.lock`

**Review by pszklarska — APPROVED** [review]

**Pull request merged**
